### ISSUE TITLE
Body parameter

### ISSUE THREAD

**Issue by bgaluszka** [apigee-127/swagger-test-templates#118]
Currently this code https://github.com/apigee-127/swagger-test-templates/blob/master/templates/request/post/post.handlebars#L24-L28

```js
        json: {
          {{#each bodyParameters}}
          {{this.name}}: 'DATA GOES HERE'{{#unless @last}},{{/unless}}
          {{/each}}
        }
```

based on this description

```yaml
      parameters:
        - name: User
          description: User
          in: body
          required: true
          schema:
            type: object
            required:
              - email
            properties:
              email:
                description: Email
                type: string 
                format: email
                default: example@example.com
```

generates body that looks like this

```json
{
    User: {
        email: example@example.com
    }
}
```

but I think it should look like this

```json
{
    email: example@example.com
}
```

this is because by http://swagger.io/specification/#parameterObject body is `The payload that's appended to the HTTP request. Since there can only be one payload, there can only be one body parameter. The name of the body parameter has no effect on the parameter itself and is used for documentation purposes only.`.
